### ISSUE TITLE
test coverage 

### ISSUE THREAD

**Issue by annmedvid** [druvisc/github-gql-api-stargazers#1]
Hi! Thank you for performing this test task. Can you please add also few tests to cover existing functionality?

**Comment by druvisc** [comment]
Hi, @annmedvid! Thank you for looking into it! I've created a PR ([Add e2e tests](https://github.com/druvisc/github-gql-api-stargazers/pull/2)) to tackle this issue.

**Comment by annmedvid** [comment]
Thank you for quick update @druvisc. May I ask you why you decided to add 2e2 tests instead of unit tests?  I will ask you to  add unit tests as well (one will be enough). Thank you)

**Comment by druvisc** [comment]
Depends on the use-case, but generally, in my opinion, e2e tests deliver the most value to a product in ensuring it's production ready - not much use of individually tested components if they don't work together or the product's end goal is not reached (e2e tests allow to test whole workflows).

Because of the application's simplicity and the use of an external component library (AntD), it didn't seem that there's much to [unit] test or there's value to it.

I created a PR ([Add unit tests](https://github.com/druvisc/github-gql-api-stargazers/pull/3)) to allow to write unit/component tests in Cypress and refactored one of the e2e tests to a unit test for a 'view component'.

**Comment by annmedvid** [comment]
Thank you @druvisc
